add background check

diff --git a/.github/workflows/ts-rpc-test.yml b/.github/workflows/ts-rpc-test.yml
--- a/.github/workflows/ts-rpc-test.yml
+++ b/.github/workflows/ts-rpc-test.yml
@@ -27,7 +27,27 @@ jobs:
         run: make ui/build
 
       - name: Run go-nitro RPC servers with GUI
-        run: go run ./cmd/start-rpc-servers -ui=true &> output.log &
+        run: |
+          go run ./cmd/start-rpc-servers -ui=true &> output.log &
+
+          NITRO_PID=$!
+
+          # Periodically check the status of the start-rpc-server process
+          while true; do
+          # Check if the process is still running
+          if ! ps -p $NITRO_PID > /dev/null; then
+              # If the process has stopped, check its exit code
+              wait $NITRO_PID
+              EXIT_CODE=$?
+              if [ $EXIT_CODE -ne 0 ]; then
+              echo "start-rpc-servers has failed with exit code $EXIT_CODE"
+              exit $EXIT_CODE
+              fi
+              break
+          fi
+          # Sleep for a short duration before checking again
+          sleep 5
+          done
 
       - name: Run Create Channels script
         # TODO: We could write a test specific script that creates channels and checks the results
